#!/bin/bash -e

export PATH=/home/rharper/go/bin:$PATH
which lxc
NAME=${1:-$(uuidgen)}
IMAGE=${2:-trusty-template/rootfs}
LOG=/tmp/${NAME}_lxd.log

function log {
    echo "`date -u +%s.%N` $@" | tee -a $LOG
}

LXDHOME=/var/lib/lxd/lxc
CMDHOME=`pwd`
CREATE=${CMDHOME}/create-pylxd
CLONE=${CMDHOME}/clone
DELETE=${CMDHOME}/delete-overlay
STATE=${CMDHOME}/state-pylxd

log "Cloning ${NAME}"
$CLONE ${NAME} ${IMAGE} overlayfs
log "Starting ${NAME}"
# CREATE blocks until start, but can fail
${CREATE} ${NAME} || { $DELETE $NAME; exit 1; }
log "Running 2 commands"
lxc exec ${NAME} cat /etc/issue
lxc exec ${NAME} uptime
log "Stopping ${NAME}"
lxc stop --force ${NAME}
s="`$STATE ${NAME}`"
while true; do
    if [ "${s}" != "STOPPED" -o "${s}" != "None" ]; then
       log "state is stopped or dead ($s)"
       break 
    fi 
    echo -n "."
    sleep 1
    s="`$STATE ${NAME}`"
    log "state=${s}"
done
echo -e "\n"
log "${NAME} STOPPED"
log "${NAME} Deleting ${NAME}"
$DELETE ${NAME}
log "${NAME} DONE"
