#!/bin/bash
NAME=${1:-$(uuidgen)}
IMAGE=${2:-trusty-template/rootfs}

LXDHOME=/var/lib/lxd/lxc
CMDHOME=`pwd`
CREATE=${CMDHOME}/create-pylxd
CLONE=${CMDHOME}/clone
DELETE=${CMDHOME}/delete-overlay
STATE=${CMDHOME}/state-pylxd

echo "Cloning ${NAME}"
$CLONE ${NAME} ${IMAGE} overlayfs
echo "Starting ${NAME}"
# CREATE blocks until start
${CREATE} ${NAME} || exit 1
lxc exec ${NAME} cat /etc/issue
