#!/bin/bash

NAME=${1:-$(uuidgen)}
IMAGE=${2:-trusty-template/rootfs}

function log {
    echo "`date -u +%s.%N` $@"
}

LXDHOME=/var/lib/lxd/lxc
CMDHOME=`pwd`
CREATE=${CMDHOME}/create-pylxd
CLONE=${CMDHOME}/clone
DELETE=${CMDHOME}/delete-overlay
STATE=${CMDHOME}/state-pylxd

log "Cloning ${NAME}"
$CLONE ${NAME} ${IMAGE} overlayfs
log "Starting ${NAME}"
# CREATE blocks until start
${CREATE} ${NAME} || exit 1
log "Running 2 commands"
lxc exec ${NAME} cat /etc/issue
lxc exec ${NAME} uptime
log "Stopping ${NAME}"
lxc stop --force ${NAME}
s="`$STATE ${NAME}`"
while [ "${s}" != "STOPPED" ]; do
    echo -n "."
    sleep 1
    s="`$STATE ${NAME}`"
done
echo -e "\n"
log "${NAME} STOPPED"
log "${NAME} Deleting ${NAME}"
$DELETE ${NAME}
log "${NAME} DONE"
